import { DatasetUnit, makeUnitId } from '@organon/gdsl/registry/canon'

/*
YS I.50 — taj-ja saṃskāra anya-saṃskāra-pratibandhī
Baseline: “The saṃskāra born from that (taj-ja) [truth-bearing prajñā] inhibits other saṃskāras.”

Readings and frame:
- taj-ja = ‘from that/there’ (tatra of I.48–I.49: ṛtambharā prajñā in the purified adhyātman locus)
- saṃskāra = impression/trace; here read as Model generated by Principle (prajñā)
- anya-saṃskāra-pratibandhī = inhibitor of other models/imprints
Dyad: Prajñā (Principle, universal) → Saṃskāra (Model, particular/viśeṣa).
*/

const CHUNKS_I_50 = [
  {
    id: 'ys-i-50-sutra',
    title: 'I.50 — taj-ja saṃskāra anya-saṃskāra-pratibandhī',
    source:
      'Baseline: “From that (taj-ja), a saṃskāra arises which inhibits other saṃskāras.” “That” = ṛtambharā prajñā (I.48–49) present in adhyātman.',
  },
  {
    id: 'ys-i-50-adhyatman-prajna-tajja',
    title: 'taj-ja locus: adhyātman purified by ṛtambharā prajñā',
    source:
      '(paraphrase) taj-ja points back to the there/that of I.48–49: the adhyātman locus where truth-bearing prajñā stands. From this locus a determinate saṃskāra is generated.',
  },
  {
    id: 'ys-i-50-model-principle-dyad',
    title: 'Model–Principle dyad: prajñā (Principle, universal) → saṃskāra (Model, particular)',
    source:
      '(paraphrase) Prajñā bears ṛta (Principle); it engenders a determinate saṃskāra as its Model. The Model carries viśeṣa (particular-as-such) and organizes appearance accordingly.',
  },
  {
    id: 'ys-i-50-axiomatic-model-theory',
    title: 'Axiomatic read: Principle/Theory ⟶ Model; constraints and satisfaction',
    source:
      '(paraphrase) Read prajñā as an axiomatic Principle (theory T) and saṃskāra as its Model M that satisfies T. anya-saṃskāras are competing models from other “theories” (vṛtti/kleśa bases). pratibandhī = a constraint that prevents satisfaction of incompatible models.',
  },
  {
    id: 'ys-i-50-inhibitory-dynamics',
    title: 'Dynamics: truth-born saṃskāra inhibits legacy saṃskāras',
    source:
      '(paraphrase) The saṃskāra produced by ṛtambharā prajñā suppresses prior kleshā/vṛtti-born imprints, blocking their reactivation in consciousness (competitive inhibition under a new governing Model).',
  },
  {
    id: 'ys-i-50-compatibility-criterion',
    title: 'Compatibility criterion: ṛta-aligned vs non-aligned imprints',
    source:
      '(paraphrase) Truth-born Model permits only transitions consistent with ṛta; legacy imprints that violate ṛta cannot be satisfied and are inhibited from surfacing.',
  },
  {
    id: 'ys-i-50-practice-operator',
    title: 'Operationalization: cultivating the truth-model, stabilizing inhibition',
    source:
      '(paraphrase) Through sustained dhyāna/japa, the ṛta-principle remains vivid; the corresponding saṃskāra stabilizes and holds the field, continuously inhibiting incompatible traces until only ṛta-consistent flow remains.',
  },
  {
    id: 'ys-i-50-bridge-fichte',
    title: 'Bridge — Fichte: maxim (negative freedom) implements inhibition',
    source:
      '(paraphrase) Principle (pure reason) generates a Model that conditions appearance. The maxim “abstract from mere consciousness” functions as negative freedom that inhibits competing projections (anya-saṃskāra-pratibandha).',
  },
  {
    id: 'ys-i-50-forward-nirodha',
    title: 'Forward link — toward nirodha (I.51)',
    source:
      '(paraphrase) When the truth-born saṃskāra fully inhibits others, it loses adversarial function and itself subsides (tasyāpi nirodha) → nirbīja-samādhi.',
  },
  // Fifteenth Lecture — Basic Proposition bridge (targeting I.50)
  {
    id: 'ys-i-50-lecture15-esse-living-oneness',
    title: 'L15 — Esse: immediate living oneness; no duality',
    source:
      '(paraphrase) What lives immediately is the esse—the “to be” lives as indivisible oneness that cannot go out of itself into duality. We live immediately in the act of living; therefore we are the one undivided being (in/of/through itself).',
  },
  {
    id: 'ys-i-50-lecture15-we-absolute-i',
    title: 'L15 — We as absolute I; genetic insight over empirical perception',
    source:
      '(paraphrase) Speaking objectifies the We, but this adds nothing. The one We-in-itself is characterized purely by immediate life. If being is absolute living, it is a self-enclosed I (We). Depend not on empirical consciousness but on genetic insight into life and I.',
  },
  {
    id: 'ys-i-50-lecture15-annul-disjunction',
    title: 'L15 — Annul disjunction: being = We; objectivity negated',
    source:
      '(paraphrase) Though we first placed being before us, insight grasps that being itself is absolute I/We; the remaining disjunction (being vs We) is annulled even factically. The maxim receives its law and realization: being cannot go out of itself; nor can we.',
  },
  {
    id: 'ys-i-50-lecture15-possibility-objectification',
    title: 'L15 — Possibility of objectification: empty repetition of the same We',
    source:
      '(paraphrase) No new objectifying consciousness arises with this insight, though ours could arise. Its content merely repeats the same self-enclosed I/We, unalterable—so it does not violate the law of oneness.',
  },
  {
    id: 'ys-i-50-lecture15-phenomenology-descent',
    title: 'L15 — Toward phenomenology: explain doubling; fix the insight',
    source:
      '(paraphrase) As first step of descent, inquire whence the empty repetition/doubling comes. For now, establish the insight of pure reason: being/the absolute is a self-enclosed I, unalterable.',
  },
  // Fifteenth Lecture — General review (part 2)
  {
    id: 'ys-i-50-lecture15-review2-concept-through',
    title: 'L15/R2 — Concept as pure “through”; presupposes self-subsisting being',
    source:
      '(paraphrase) Proceeding factically under an unconscious law, we arrived at the pure “through” as essence of concept; its realization presupposes a self-subsisting being.',
  },
  {
    id: 'ys-i-50-lecture15-review2-idealism-realism-maxims',
    title: 'L15/R2 — Two standpoints with maxims; both factical',
    source:
      '(paraphrase) Idealism: posit the energy of thinking the “through” as absolute (source of intuition/life). Realism: posit life-in-itself as principle. Maxims: take reflection’s fact (idealism) vs take evident content (realism). Both remain factical.',
  },
  {
    id: 'ys-i-50-lecture15-review2-higher-realism-light',
    title: 'L15/R2 — Higher realism: in-itself self-constructs and emits light',
    source:
      '(paraphrase) Focusing on the in-itself bound to life yields: it negates validity of seeing, constructs itself in immediate manifestness, and emits light—deducing both insight and light.',
  },
  {
    id: 'ys-i-50-lecture15-review2-new-idealism-claim',
    title: 'L15/R2 — New idealism’s claim and self-misplacement',
    source:
      '(paraphrase) We might think the in-itself appears through our reflection’s energy as basic principle. Realism (i.e., we) counters: appeal to consciousness cannot genetically ground thinking; but consciousness can be derived as modification of insight/light from the in-itself.',
  },
  {
    id: 'ys-i-50-lecture15-review2-higher-maxim',
    title: 'L15/R2 — Higher maxim: abstract from immediate consciousness',
    source:
      '(paraphrase) Do not credit simple immediate consciousness (even if factically inescapable); abstract from it in matters of truth.',
  },
  {
    id: 'ys-i-50-lecture15-review2-projection-gap',
    title: 'L15/R2 — Effect to remove: projection through an irrational gap',
    source:
      '(paraphrase) What to remove: absolute projection of an object with inexplicable origin—between act and object all is dark/empty: proiectio per hiatum irrationale.',
  },
  // Fifteenth Lecture — General review (part 3): maxim, non-genesis, and realism under judgment
  {
    id: 'ys-i-50-lecture15-review3-maxim-absolute-genesis',
    title: 'L15/R3 — Maxim: immediate consciousness insufficient; absolute genesis vs projection',
    source:
      '(paraphrase) Clarity rests on impartially establishing the maxim: immediate consciousness is insufficient; its basic law (proiectio per hiatum irrationale) does not suffice. This maxim = the principle of absolute genesis: what is not realized genetically is not permitted; hence projection-through-gap is excluded.',
  },
  {
    id: 'ys-i-50-lecture15-review3-non-genesis-factical',
    title: 'L15/R3 — Non-genesis is unavoidable factically; method: ignore and abstain',
    source:
      '(paraphrase) Non-genesis remains an unavoidable fact of consciousness. Earlier path: divide the illusion and destroy it piecemeal (hard but reaches the goal). Better: know its origin, let it operate harmlessly, ignore it, abstain from its results—thereby access insight immediately.',
  },
  {
    id: 'ys-i-50-lecture15-review3-realism-judged',
    title: 'L15/R3 — Realism judged by its maxim: in-itself needs not-in-itself → unity-in-relation',
    source:
      '(paraphrase) The “in-itself,” taken as original and independent, proves incomprehensible without a not-in-itself; hence it is only intelligible via its correlate. Unity must be unity-in-relation (the “through,” with its recognized fivefoldness). Admitting oneness makes the terms generate genetically, but oneness itself is not thereby genetic—so it enters as a projection per hiatum, violating realism’s own principle.',
  },
]

const HLOS_I_50 = [
  {
    id: 'ys-i-50-hlo-baseline',
    chunkId: 'ys-i-50-sutra',
    label: 'Baseline',
    clauses: [
      "tag('sutra','I.50')","tag('lens','yoga')","tag('link','I.48→I.49→I.50')",
      'tajJa := from(prajna_rtambhara@adhyatman)',
      'arises(samskara_truthBorn := tajJa)',
      'effect(samskara_truthBorn := inhibit(anyaSamskara))',
    ],
  },
  {
    id: 'ys-i-50-hlo-adhyatman-prajna-tajja',
    chunkId: 'ys-i-50-adhyatman-prajna-tajja',
    label: 'taj-ja locus = adhyātman with ṛtambharā prajñā',
    clauses: [
      "tag('sutra','I.50')","tag('lens','yoga')",
      'locate(tajJa := locus(adhyatman ∧ prajna_rtambhara))',
      'generate(samskara := from(locus))',
    ],
  },
  {
    id: 'ys-i-50-hlo-model-principle-dyad',
    chunkId: 'ys-i-50-model-principle-dyad',
    label: 'Universal–particular: Principle → Model (viśeṣa)',
    clauses: [
      "tag('sutra','I.50')","tag('lens','prajna')","tag('link','I.49:viśeṣa')",
      'prajna(Principle: universalTruth) ⇒ generate(samskara(Model: determinateParticular))',
      'bind(universal, particular := visesa)',
    ],
  },
  {
    id: 'ys-i-50-hlo-axiomatic-model-theory',
    chunkId: 'ys-i-50-axiomatic-model-theory',
    label: 'Axiomatic mapping: T ⟶ M; pratibandha as constraint',
    clauses: [
      "tag('sutra','I.50')","tag('lens','model-theory')",
      'map(prajna → Theory(T)) ∧ map(samskara → Model(M))',
      'anyaSamskara := models(from: {vritti, klesha})',
      'pratibandhi := constraint(T) ⊣ satisfy(anyaSamskara)',
    ],
  },
  {
    id: 'ys-i-50-hlo-inhibitory-dynamics',
    chunkId: 'ys-i-50-inhibitory-dynamics',
    label: 'Inhibition dynamics: competitive suppression',
    clauses: [
      "tag('sutra','I.50')","tag('lens','yoga')","tag('topic','vritti/klesha')",
      'samskara_truthBorn ⊣ suppress(legacy := from(vritti ∪ klesha))',
      'prevent(reactivation(legacy), in: field(consciousness))',
    ],
  },
  {
    id: 'ys-i-50-hlo-compatibility-criterion',
    chunkId: 'ys-i-50-compatibility-criterion',
    label: 'Criterion: allow(ṛta-consistent) / block(ṛta-inconsistent)',
    clauses: [
      "tag('sutra','I.50')","tag('lens','prajna')",
      'allow(flow := transitions | consistentWith(rta))',
      'block(flow := transitions | violate(rta))',
    ],
  },
  {
    id: 'ys-i-50-hlo-practice-operator',
    chunkId: 'ys-i-50-practice-operator',
    label: 'Operator: stabilize the truth-model via practice',
    clauses: [
      "tag('sutra','I.50')","tag('lens','sadhana')",
      'practice := sustain({dhyana, japa}) ⇒ vivify(prajna) ⇒ stabilize(samskara_truthBorn)',
      'maintain(inhibition) until(only(rta-consistent flow))',
    ],
  },
  {
    id: 'ys-i-50-hlo-bridge-fichte',
    chunkId: 'ys-i-50-bridge-fichte',
    label: 'Fichtean bridge: maxim → inhibition',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','maxim/appearance')",
      'Principle(pureReason) ⇒ Model(conditioningAppearance)',
      'maxim(“abstract from mere consciousness”) ⇒ inhibit(competingProjections)',
      'equate(pratibandha, negativeFreedom@method)',
    ],
  },
  {
    id: 'ys-i-50-hlo-forward-nirodha',
    chunkId: 'ys-i-50-forward-nirodha',
    label: 'Toward nirodha (I.51)',
    clauses: [
      "tag('sutra','I.50')","tag('lens','yoga')","tag('link','I.50→I.51')",
      'if(totalInhibition(anyaSamskara)) ⇒ tend(nirodha)',
      'later: cease(samskara_truthBorn) when(purposeComplete)',
    ],
  },
  // Fifteenth Lecture — HLOs
  {
    id: 'ys-i-50-hlo-lecture15-esse-living-oneness',
    chunkId: 'ys-i-50-lecture15-esse-living-oneness',
    label: 'Esse = immediate living oneness; no duality',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','being/life')",
      'esse := livingImmediate(one)',
      'forbid(duality) ; being := cannot(exitItself)',
      'we := liveIn(actOfLiving) ⇒ are(being_one)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-we-absolute-i',
    chunkId: 'ys-i-50-lecture15-we-absolute-i',
    label: 'We = absolute I; genetic insight > empirical',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','insight/I')",
      'objectify(we) ⇒ addsNothing',
      'we_in_itself := characterizedBy(immediateLife)',
      'if(being := absoluteLiving) ⇒ being ≡ I(selfEnclosed) ≡ We',
      'prefer(geneticInsight, over: empiricalConsciousness)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-annul-disjunction',
    chunkId: 'ys-i-50-lecture15-annul-disjunction',
    label: 'Annul disjunction: being ≡ We; maxim realized',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','law/maxim')",
      'insight: being ≡ We ⇒ annul(disjunction{being, we})',
      'proveRealize(maxim: ¬objectifyBeing) ; cannot(exitSelf)(being ∧ we)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-possibility-objectification',
    chunkId: 'ys-i-50-lecture15-possibility-objectification',
    label: 'Possible objectification: empty repetition of the same We',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','appearance')",
      'noNewObjectifyingConsciousness with(insight)',
      'possible(ourObjectification) ⇒ content := repeat(sameSelfEnclosedWe) ∧ unalterable',
      'lawPreserved(oneness)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-phenomenology-descent',
    chunkId: 'ys-i-50-lecture15-phenomenology-descent',
    label: 'Set up phenomenology; fix the insight',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('stance','phenomenology')",
      'task := explain(doubling/repetition)',
      'fixInsight: absolute := selfEnclosedI ∧ unalterable',
    ],
  },
  // Fifteenth Lecture — General review (part 2) HLOs
  {
    id: 'ys-i-50-hlo-lecture15-review2-concept-through',
    chunkId: 'ys-i-50-lecture15-review2-concept-through',
    label: 'Concept as “through” presupposes being',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','concept/being')",
      'essence(concept) := pureThrough',
      'realization(concept) ⇒ presuppose(being:selfSubsisting)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review2-idealism-realism-maxims',
    chunkId: 'ys-i-50-lecture15-review2-idealism-realism-maxims',
    label: 'Idealism vs realism; maxims; both factical',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('stance','review')",
      'idealism := posit(energyOfThinking_through := absolute)',
      'realism := posit(lifeInItself := principle)',
      'maxim(idealism) := trust(factOfReflection)',
      'maxim(realism) := trust(evidentContent)',
      'both := factical',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review2-higher-realism-light',
    chunkId: 'ys-i-50-lecture15-review2-higher-realism-light',
    label: 'Higher realism: in-itself constructs and emits light',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','light/insight')",
      'inItself := negate(validity(seeing→it))',
      'construct(itself) ∧ emit(light := immediateManifestness)',
      'deduce({insight, light})',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review2-new-idealism-claim',
    chunkId: 'ys-i-50-lecture15-review2-new-idealism-claim',
    label: 'Counter: derive consciousness from light; not vice versa',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','derivation')",
      'claim(newIdealism) := reflectionEnergy ⇒ firstLink',
      'reply(realism) := cannot(derive(thinking, from: awareness)) ∧ can(derive(consciousness, from: light@inItself))',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review2-higher-maxim',
    chunkId: 'ys-i-50-lecture15-review2-higher-maxim',
    label: 'Higher maxim: abstract from immediacy',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','maxim')",
      'rule := ¬credit(immediateConsciousness) ∧ abstractFrom(it)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review2-projection-gap',
    chunkId: 'ys-i-50-lecture15-review2-projection-gap',
    label: 'Remove: proiectio per hiatum irrationale',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','appearance/projection')",
      'effect(consciousness) := absoluteProjection(object) ∧ gap(irrational) between {act, object}',
      'maxim := remove(effect)',
    ],
  },
  // Fifteenth Lecture — General review (part 3) HLOs
  {
    id: 'ys-i-50-hlo-lecture15-review3-maxim-absolute-genesis',
    chunkId: 'ys-i-50-lecture15-review3-maxim-absolute-genesis',
    label: 'Maxim: immediate consciousness insufficient; absolute genesis only',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','method/maxim')",
      'rule := insufficient(immediateConsciousness)',
      'principle := absoluteGenesis',
      'forbid(proiectioPerHiatumIrrationale)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review3-non-genesis-factical',
    chunkId: 'ys-i-50-lecture15-review3-non-genesis-factical',
    label: 'Non-genesis: unavoidable factical; ignore and abstain',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('topic','phenomenology/method')",
      'nonGenesis := unavoidable(factical)',
      'oldMethod := divideIllusion ⊢ destroy(piecewise) // harder path',
      'newMethod := letOperatePeacefully ∧ ignore ∧ abstainFrom(results) ⇒ access(insight: immediate)',
    ],
  },
  {
    id: 'ys-i-50-hlo-lecture15-review3-realism-judged',
    chunkId: 'ys-i-50-lecture15-review3-realism-judged',
    label: 'Judgment: in-itself needs its correlate; unity-in-relation; gap at oneness',
    clauses: [
      "tag('sutra','I.50')","tag('lens','fichte')","tag('stance','adjudication')",
      'inItself ⇒ incomprehensible(¬with:notInItself)',
      'unity := unityInRelation(“through” ∧ fivefoldness)',
      'admit(oneness) ⇒ terms(self-generate: genetic)',
      'but ¬genetic(oneness) ⇒ entersAs(proiectioPerHiatum) ⇒ violates(ownPrinciple: realism)',
    ],
  },
]

// Export unit only
export const YS_I_50_UNIT: DatasetUnit = {
  id: makeUnitId('i.50'),
  title: 'YS I.50 — taj-ja saṃskāra anya-saṃskāra-pratibandhī',
  scope: 'essence',
  logosMode: 'samskara',
  synthesis: 'pre-factum',
  faculty: 'buddhi',
  lens: 'yoga',
  chunks: CHUNKS_I_50 as any,
  hlos: HLOS_I_50 as any,
}
