// ALL Default* implementations generated by the Mega Macro Factory!
// This replaces ~250 lines of hand-written boilerplate with a single macro invocation.
//
// The generate_primitive_values!() macro generates:
// - DefaultLongValue (scalar i64)
// - DefaultFloatingPointValue (scalar f64)
// - DefaultLongArray (Vec<i64>)
// - DefaultIntLongArray (Vec<i32> → i64)
// - DefaultShortLongArray (Vec<i16> → i64)
// - DefaultByteLongArray (Vec<u8> → i64)
// - DefaultDoubleArray (Vec<f64>)
// - DefaultFloatArray (Vec<f32> → f64)

generate_primitive_values!();
